![Factories creating emissions](pollution.jpg)

Photo by Maxim Tolchinskiy on Unsplash
  
When factoring heat generation required for the manufacturing and transportation of products, _Greenhouse gas emissions attributable to products, from food to sneakers to appliances, make up more than 75% of global emissions._ [The Carbon Catalogue](https://www.nature.com/articles/s41597-022-01178-9)

Our data, which is publicly available on [nature.com](https://www.nature.com/articles/s41597-022-01178-9), contains product carbon footprints (PCFs) for various companies. PCFs are the greenhouse gas emissions attributable to a given product, measured in CO<sub>2</sub> (carbon dioxide equivalent).

This data is stored in a PostgreSQL database containing one table, `product_emissions`, which looks at PCFs by product as well as the stage of production that these emissions occurred. Here's a snapshot of what `product_emissions` contains in each column:

### `product_emissions`

| field                              | data type |
|------------------------------------|-----------|
| `id`                                 | `VARCHAR`   |
| `year`                               | `INT`       |
| `product_name`                       | `VARCHAR`   |
| `company`                            | `VARCHAR`   |
| `country`                            | `VARCHAR`   |
| `industry_group`                     | `VARCHAR`   |
| `weight_kg`                          | `NUMERIC`   |
| `carbon_footprint_pcf`               | `NUMERIC`   |
| `upstream_percent_total_pcf`         | `VARCHAR`   |
| `operations_percent_total_pcf`       | `VARCHAR`   |
| `downstream_percent_total_pcf`       | `VARCHAR`   |

You'll use this data to examine the carbon footprint of each industry in the dataset!

In [3]:
SELECT *
FROM product_emissions
LIMIT 5;

             id  year  ... operations_percent_total_pcf downstream_percent_total_pcf
0  10056-1-2014  2014  ...                       30.00%                       12.50%
1  10056-1-2015  2015  ...                       30.00%                       12.50%
2  10222-1-2013  2013  ...                       17.36%                        2.01%
3  10261-1-2017  2017  ...                        5.51%                       63.84%
4  10261-2-2017  2017  ...                        4.51%                       70.41%

[5 rows x 11 columns]

In [4]:
SELECT weight_kg, carbon_footprint_pcf, upstream_percent_total_pcf, operations_percent_total_pcf, downstream_percent_total_pcf
FROM product_emissions
LIMIT 5;

   weight_kg  ...  downstream_percent_total_pcf
0     0.7485  ...                        12.50%
1     0.7485  ...                        12.50%
2    20.6800  ...                         2.01%
3   110.0000  ...                        63.84%
4   110.0000  ...                        70.41%

[5 rows x 5 columns]

In [15]:
SELECT MAX(year) as Recent_year
FROM product_emissions;

   recent_year
0         2017

In [16]:
SELECT industry_group,
		COUNT(DISTINCT company) as num_companies, 	
		ROUND(SUM(carbon_footprint_pcf), 1) AS total_industry_footprint
FROM product_emissions
WHERE year IN 
			(SELECT MAX(year) 
			FROM product_emissions)
GROUP BY industry_group
ORDER BY total_industry_footprint DESC;

                       industry_group  num_companies  total_industry_footprint
0                           Materials              3                  107129.0
1                       Capital Goods              2                   94942.7
2     Technology Hardware & Equipment              4                   21865.1
3            Food, Beverage & Tobacco              1                    3161.5
4  Commercial & Professional Services              1                     740.6
5                 Software & Services              1                     690.0

In [17]:
SELECT industry_group,
		COUNT(DISTINCT company) as num_companies, 	
		ROUND(SUM(carbon_footprint_pcf), 1) AS total_industry_footprint
FROM product_emissions
WHERE year IN 
			(SELECT MAX(year) 
			FROM product_emissions)
GROUP BY industry_group
ORDER BY total_industry_footprint DESC;

                       industry_group  num_companies  total_industry_footprint
0                           Materials              3                  107129.0
1                       Capital Goods              2                   94942.7
2     Technology Hardware & Equipment              4                   21865.1
3            Food, Beverage & Tobacco              1                    3161.5
4  Commercial & Professional Services              1                     740.6
5                 Software & Services              1                     690.0